### ISSUE TITLE
Optional form elements have aria-required attributes set to true

### ISSUE THREAD

**Issue by cfq** [UKHomeOffice/brp_app#343]
Even though not all form elements are required, all of them have aria-required set to true. 

For example on /collection/contact-details, Phone number field is optional but it is marked as aria-required. It would be good to have a look at the source of the problem and give a quick swipe across the pages.

**Comment by daniel-ac-martin** [comment]
I believe this is a bug in [passports-template-mixins].

**Comment by daniel-ac-martin** [comment]
https://github.com/UKHomeOffice/passports-template-mixins/pull/54

**Comment by gavboulton** [comment]
If you need to do something in the meantime you can set `required: false` in your field config.

**Comment by daniel-ac-martin** [comment]
The PR has been merged, with a new version on template-mixins published. (Thanks again @gavboulton.)

@easternbloc: We should bump the version in hof, then bump the version of hof in brp_app, and this issue will be fixed.

**Comment by daniel-ac-martin** [comment]
Fixed. Will go live in the next release.
Thanks again for bringing this to our attention @cfq.
There would have been similar problems in pretty much all forms using the hmpo modules, including the hof forms! So they will all be fixed when they update their libraries.
