### ISSUE TITLE
Add redis sentinel support

### ISSUE THREAD

**Issue by vaijab** [UKHomeOffice/brp_app#63]
Add redis sentinel support. Redis sentinal allows us to have HA redis.

**Comment by vaijab** [comment]
We can probably park this for now. We should be OK with using a single redis instance for MVP.

**Comment by easternbloc** [comment]
We can leave it here as it'll need doing. But agreed on the single instance for now.

**Comment by vaijab** [comment]
> it'll need doing

absolutely. Thanks.
